
project_id = "kdliebqlebfqjcbjxypr"

[functions.send-email]
verify_jwt = true

[auth]
site_url = "https://rockematic-kdliebqlebfqjcbjxypr.lovable.dev"
additional_redirect_urls = [
  "https://rockematic-kdliebqlebfqjcbjxypr.lovable.dev/auth",
  "https://rockematic-kdliebqlebfqjcbjxypr.lovable.dev/dashboard",
  "http://localhost:5173",
  "http://localhost:5173/auth",
  "http://localhost:5173/dashboard"
]

