// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdliebqlebfqjcbjxypr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbGllYnFsZWJmcWpjYmp4eXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTM1OTEsImV4cCI6MjA2MDU2OTU5MX0.G1DM702rnP6kejrgEj6x17oOn9c6pBwuh8phOqaxbzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);